### ISSUE TITLE
XML files are continuously changing 

### ISSUE THREAD

**Issue by morning9393** [SafeRL-Lab/Robust-Gymnasium#4]
While training with Ant-v4, I noticed that the "Robust-Gymnasium/robust_gymnasium/envs/robust_mujoco/assets/ant.xml" is continuously changing. At the same time, if I try to start a new experiment on Ant-v4, I will be possible to get an XML error "Error=XML_ERROR_EMPTY_DOCUMENT ErrorID=13 (0xd) Line number=0", at:
Robust-Gymnasium/robust_gymnasium/envs/robust_mujoco/mujoco_env.py", line 229, in _initialize_simulation
    model = mujoco.MjModel.from_xml_path(self.fullpath)

**Comment by chauncygu** [comment]
Thanks! We have fixed the issue; please use the latest version
