### ISSUE TITLE
How to setup when to perturb?

### ISSUE THREAD

**Issue by sihongho** [SafeRL-Lab/Robust-Gymnasium#5]
Hi, I didn't find parameters to setup when to perturb in the configuration. When will you release a more detailed instruction or tutorial? Thanks.

**Comment by chauncygu** [comment]
Hi sihongho,

Thanks for your message; we will release a tutorial soon; let's keep in touch.

**Comment by chauncygu** [comment]
You can use this to set robust parameters: https://github.com/SafeRL-Lab/Robust-Gymnasium/tree/main/robust_gymnasium/configs 

or each example's config: https://github.com/SafeRL-Lab/Robust-Gymnasium/blob/main/examples/robust_action/mujoco/test_render.py

I hope this helps to address your question.

Thanks again for your messages.
