### ISSUE TITLE
MAPPO code

### ISSUE THREAD

**Issue by prinshul** [SafeRL-Lab/Robust-Gymnasium#9]
Hi,

Is it possible to share MA-Mujoco MAPPO/IPPO code with state action reward etc. robustness?

**Comment by chauncygu** [comment]
Dear prinshul,

Thank you for your comments.

Here is the code for MAPPO: https://github.com/zoeyuchao/mappo. I hope this will be helpful. If you have any additional comments or suggestions, please feel free to let us know.

Best regards,

Shangding
